"""models_dev_capability_attributes

Revision ID: 35c396a461bc
Revises: 2833ae93e0e4
Create Date: 2026-09-04 08:18:14.743738

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "35c396a461bc"
down_revision: str | None = "2833ae93e0e4"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("models", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("attachment", sa.Boolean(), server_default=sa.false(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("reasoning", sa.Boolean(), server_default=sa.false(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("tool_call", sa.Boolean(), server_default=sa.false(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("structured_output", sa.Boolean(), server_default=sa.false(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("temperature", sa.Boolean(), server_default=sa.false(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("experimental", sa.Boolean(), server_default=sa.false(), nullable=False)
        )
        batch_op.add_column(
            sa.Column("open_weights", sa.Boolean(), server_default=sa.false(), nullable=False)
        )
        batch_op.add_column(sa.Column("status", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("family", sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column("knowledge", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("release_date", sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column("max_output_tokens", sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("models", schema=None) as batch_op:
        batch_op.drop_column("max_output_tokens")
        batch_op.drop_column("release_date")
        batch_op.drop_column("knowledge")
        batch_op.drop_column("family")
        batch_op.drop_column("status")
        batch_op.drop_column("open_weights")
        batch_op.drop_column("experimental")
        batch_op.drop_column("temperature")
        batch_op.drop_column("structured_output")
        batch_op.drop_column("tool_call")
        batch_op.drop_column("reasoning")
        batch_op.drop_column("attachment")

    # ### end Alembic commands ###
