"""systemone capability

Revision ID: 78a18792d186
Revises: a1f4c7d92b30
Create Date: 2026-10-04 23:07:28.043797

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "78a18792d186"
down_revision: str | None = "a1f4c7d92b30"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("models", schema=None) as batch_op:
        batch_op.add_column(
            sa.Column("supports_systemone", sa.Boolean(), server_default=sa.false(), nullable=False)
        )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("models", schema=None) as batch_op:
        batch_op.drop_column("supports_systemone")

    # ### end Alembic commands ###
