"""initial schema

Revision ID: b3f3198d9d83
Revises:
Create Date: 2026-08-22 01:23:44.583177

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "b3f3198d9d83"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "audit_sequence",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("current_sequence", sa.Integer(), nullable=False),
        sa.Column("last_hash", sa.String(length=64), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "mcp_servers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("command", sa.String(length=500), nullable=True),
        sa.Column("args", sa.JSON(), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=True),
        sa.Column("env", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("proxy_url", sa.String(length=500), nullable=True),
        sa.Column("server_metadata", sa.JSON(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("updated_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("mcp_servers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_mcp_servers_name"), ["name"], unique=True)

    op.create_table(
        "models",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("timeout", sa.Float(), nullable=True),
        sa.Column("max_retries", sa.Integer(), nullable=True),
        sa.Column("input_cost_per_1m", sa.Float(), nullable=True),
        sa.Column("output_cost_per_1m", sa.Float(), nullable=True),
        sa.Column("cached_read_cost_per_1m", sa.Float(), nullable=True),
        sa.Column("cached_write_cost_per_1m", sa.Float(), nullable=True),
        sa.Column("audio_input_cost_per_1m", sa.Float(), nullable=True),
        sa.Column("audio_output_cost_per_1m", sa.Float(), nullable=True),
        sa.Column("image_input_cost_per_1m", sa.Float(), nullable=True),
        sa.Column("cost_per_image", sa.Float(), nullable=True),
        sa.Column("audio_cost_per_minute", sa.Float(), nullable=True),
        sa.Column("tts_cost_per_1m_chars", sa.Float(), nullable=True),
        sa.Column("web_search_cost_per_1k", sa.Float(), nullable=True),
        sa.Column("icon_url", sa.String(length=500), nullable=True),
        sa.Column("description", sa.Text(), nullable=True),
        sa.Column("homepage_url", sa.String(length=500), nullable=True),
        sa.Column("context_length", sa.Integer(), nullable=True),
        sa.Column("model_metadata", sa.JSON(), nullable=False),
        sa.Column("auto_eligible", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("quality_tier", sa.String(length=20), nullable=True),
        sa.Column("routing_assignments", sa.JSON(), nullable=True),
        sa.Column("supports_images", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column(
            "supports_image_generation", sa.Boolean(), server_default=sa.false(), nullable=False
        ),
        sa.Column("supports_tts", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("supports_stt", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("supports_embedding", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("supports_realtime", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("models", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_models_name"), ["name"], unique=True)

    op.create_table(
        "providers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("type", sa.String(length=50), nullable=False),
        sa.Column("api_key", sa.String(length=500), nullable=False),
        sa.Column("base_url", sa.String(length=500), nullable=True),
        sa.Column("api_version", sa.String(length=50), nullable=True),
        sa.Column("timeout", sa.Float(), nullable=False),
        sa.Column("rate_limit", sa.Integer(), nullable=True),
        sa.Column("custom_headers", sa.JSON(), nullable=False),
        sa.Column("provider_models", sa.JSON(), nullable=False),
        sa.Column("enabled", sa.Boolean(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("provider_metadata", sa.JSON(), nullable=False),
        sa.Column("definition_path", sa.String(length=500), nullable=True),
        sa.Column("icon_url", sa.String(length=500), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("providers", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_providers_name"), ["name"], unique=True)

    op.create_table(
        "request_logs",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.Float(), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("endpoint", sa.String(length=500), nullable=False),
        sa.Column("log_type", sa.String(length=20), nullable=True),
        sa.Column("method", sa.String(length=16), nullable=False),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column("user_identity", sa.String(length=200), nullable=True),
        sa.Column("model", sa.String(length=200), nullable=True),
        sa.Column("provider", sa.String(length=100), nullable=True),
        sa.Column("request_headers", sa.JSON(), nullable=False),
        sa.Column("request_body", sa.JSON(), nullable=False),
        sa.Column("response_headers", sa.JSON(), nullable=False),
        sa.Column("response_body", sa.JSON(), nullable=False),
        sa.Column("error_message", sa.Text(), nullable=True),
        sa.Column("error_stack_trace", sa.Text(), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("cache_creation_input_tokens", sa.Integer(), nullable=True),
        sa.Column("cache_read_input_tokens", sa.Integer(), nullable=True),
        sa.Column("cached_prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("cache_savings_usd", sa.Float(), nullable=True),
        sa.Column("audio_input_tokens", sa.Integer(), nullable=True),
        sa.Column("audio_output_tokens", sa.Integer(), nullable=True),
        sa.Column("log_metadata", sa.JSON(), nullable=False),
        sa.Column("api_key_name", sa.String(length=255), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("ttft_ms", sa.Integer(), nullable=True),
        sa.Column("request_body_compressed", sa.LargeBinary(), nullable=True),
        sa.Column("response_body_compressed", sa.LargeBinary(), nullable=True),
        sa.Column("request_body_compression", sa.String(length=20), nullable=True),
        sa.Column("response_body_compression", sa.String(length=20), nullable=True),
        sa.Column("request_body_original_size", sa.Integer(), nullable=True),
        sa.Column("response_body_original_size", sa.Integer(), nullable=True),
        sa.Column("client_ip", sa.String(length=45), nullable=True),
        sa.Column("user_agent", sa.String(length=500), nullable=True),
        sa.Column("session_id", sa.String(length=64), nullable=True),
        sa.Column("auth_method", sa.String(length=20), nullable=True),
        sa.Column("server_hostname", sa.String(length=255), nullable=True),
        sa.Column("service_name", sa.String(length=100), nullable=True),
        sa.Column("service_version", sa.String(length=50), nullable=True),
        sa.Column("event_type", sa.String(length=30), nullable=True),
        sa.Column("action_category", sa.String(length=20), nullable=True),
        sa.Column("resource_type", sa.String(length=30), nullable=True),
        sa.Column("resource_id", sa.String(length=255), nullable=True),
        sa.Column("outcome", sa.String(length=20), nullable=True),
        sa.Column("sequence_number", sa.Integer(), nullable=True),
        sa.Column("content_hash", sa.String(length=64), nullable=True),
        sa.Column("previous_hash", sa.String(length=64), nullable=True),
        sa.Column("content_hash_version", sa.Integer(), server_default="2", nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("request_id"),
    )
    with op.batch_alter_table("request_logs", schema=None) as batch_op:
        batch_op.create_index("ix_request_logs_client_ip", ["client_ip"], unique=False)
        batch_op.create_index("ix_request_logs_cost_usd", ["cost_usd"], unique=False)
        batch_op.create_index("ix_request_logs_event_type", ["event_type"], unique=False)
        batch_op.create_index("ix_request_logs_model", ["model"], unique=False)
        batch_op.create_index("ix_request_logs_outcome", ["outcome"], unique=False)
        batch_op.create_index("ix_request_logs_provider", ["provider"], unique=False)
        batch_op.create_index("ix_request_logs_request_id", ["request_id"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_request_logs_sequence_number"), ["sequence_number"], unique=False
        )
        batch_op.create_index("ix_request_logs_status_code", ["status_code"], unique=False)
        batch_op.create_index("ix_request_logs_timestamp", ["timestamp"], unique=False)
        batch_op.create_index(
            "ix_request_logs_timestamp_sequence", ["timestamp", "sequence_number"], unique=False
        )
        batch_op.create_index(
            "ix_request_logs_timestamp_status", ["timestamp", "status_code"], unique=False
        )
        batch_op.create_index("ix_request_logs_total_tokens", ["total_tokens"], unique=False)
        batch_op.create_index(
            "ix_request_logs_ts_status_model", ["timestamp", "status_code", "model"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_request_logs_user_id"), ["user_id"], unique=False)

    op.create_table(
        "server_config",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("key", sa.String(length=100), nullable=False),
        sa.Column("value", sa.JSON(), nullable=False),
        sa.Column("description", sa.Text(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("server_config", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_server_config_key"), ["key"], unique=True)

    op.create_table(
        "users",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("username", sa.String(length=100), nullable=False),
        sa.Column("password_hash", sa.String(length=255), nullable=False),
        sa.Column("role", sa.String(length=20), server_default="viewer", nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("must_change_password", sa.Boolean(), server_default=sa.false(), nullable=False),
        sa.Column("token_version", sa.Integer(), server_default="0", nullable=False),
        sa.Column("allowed_models", sa.JSON(), nullable=True),
        sa.Column("budget_usd", sa.Float(), nullable=True),
        sa.Column("budget_period", sa.String(length=10), nullable=True),
        sa.Column("budget_reset_day", sa.Integer(), nullable=True),
        sa.Column("budget_reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("tracing_config", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_users_username"), ["username"], unique=True)

    op.create_table(
        "api_keys",
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("key_hash", sa.String(length=255), nullable=False),
        sa.Column("allowed_models", sa.JSON(), nullable=True),
        sa.Column("allowed_mcp_servers", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("budget_usd", sa.Float(), nullable=True),
        sa.Column("budget_period", sa.String(length=10), nullable=True),
        sa.Column("budget_reset_day", sa.Integer(), nullable=True),
        sa.Column("budget_reset_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column("rate_limit_rpm", sa.Integer(), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("name"),
        sa.UniqueConstraint("key_hash"),
    )
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_api_keys_user_id"), ["user_id"], unique=False)

    op.create_table(
        "model_experience",
        sa.Column("name", sa.String(length=100), nullable=False),
        sa.Column("samples", sa.Integer(), nullable=False),
        sa.Column("reward_mean", sa.Float(), nullable=False),
        sa.Column("latency", sa.Float(), nullable=False),
        sa.Column("reliability", sa.Float(), nullable=False),
        sa.Column("feedback", sa.Float(), nullable=False),
        sa.Column("cache_affinity", sa.Float(), nullable=False),
        sa.Column("updated_at", sa.Float(), nullable=False),
        sa.ForeignKeyConstraint(["name"], ["models.name"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("name"),
    )
    op.create_table(
        "model_providers",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("model_id", sa.Integer(), nullable=False),
        sa.Column("provider_id", sa.Integer(), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("provider_model_name", sa.String(length=200), nullable=True),
        sa.Column("input_cost_per_1m", sa.Float(), nullable=True),
        sa.Column("output_cost_per_1m", sa.Float(), nullable=True),
        sa.Column("cached_read_cost_per_1m", sa.Float(), nullable=True),
        sa.Column("cached_write_cost_per_1m", sa.Float(), nullable=True),
        sa.Column("audio_input_cost_per_1m", sa.Float(), nullable=True),
        sa.Column("audio_output_cost_per_1m", sa.Float(), nullable=True),
        sa.Column("image_input_cost_per_1m", sa.Float(), nullable=True),
        sa.Column("cost_per_image", sa.Float(), nullable=True),
        sa.Column("audio_cost_per_minute", sa.Float(), nullable=True),
        sa.Column("tts_cost_per_1m_chars", sa.Float(), nullable=True),
        sa.Column("web_search_cost_per_1k", sa.Float(), nullable=True),
        sa.Column("parameter_overrides", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["model_id"], ["models.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["provider_id"], ["providers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("model_providers", schema=None) as batch_op:
        batch_op.create_index(
            "ix_model_providers_model_priority", ["model_id", "priority"], unique=False
        )
        batch_op.create_index(
            "ix_model_providers_provider_model_name", ["provider_model_name"], unique=False
        )

    op.create_table(
        "usage_records",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("timestamp", sa.Float(), nullable=False),
        sa.Column("request_id", sa.String(length=64), nullable=True),
        sa.Column("model", sa.String(length=200), nullable=True),
        sa.Column("provider", sa.String(length=100), nullable=True),
        sa.Column("prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("completion_tokens", sa.Integer(), nullable=True),
        sa.Column("total_tokens", sa.Integer(), nullable=True),
        sa.Column("cost_usd", sa.Float(), nullable=True),
        sa.Column("cache_creation_input_tokens", sa.Integer(), nullable=True),
        sa.Column("cache_read_input_tokens", sa.Integer(), nullable=True),
        sa.Column("cached_prompt_tokens", sa.Integer(), nullable=True),
        sa.Column("cache_savings_usd", sa.Float(), nullable=True),
        sa.Column("audio_input_tokens", sa.Integer(), nullable=True),
        sa.Column("audio_output_tokens", sa.Integer(), nullable=True),
        sa.Column("response_time_ms", sa.Integer(), nullable=True),
        sa.Column("status_code", sa.Integer(), nullable=True),
        sa.Column("user_identity", sa.String(length=200), nullable=True),
        sa.Column("api_key_name", sa.String(length=255), nullable=True),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("is_streaming", sa.Boolean(), nullable=False),
        sa.Column("ttft_ms", sa.Integer(), nullable=True),
        sa.Column("log_type", sa.String(length=20), nullable=True),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("usage_records", schema=None) as batch_op:
        batch_op.create_index("ix_usage_records_api_key", ["api_key_name"], unique=False)
        batch_op.create_index("ix_usage_records_model", ["model"], unique=False)
        batch_op.create_index("ix_usage_records_provider", ["provider"], unique=False)
        batch_op.create_index(
            batch_op.f("ix_usage_records_request_id"), ["request_id"], unique=False
        )
        batch_op.create_index("ix_usage_records_timestamp", ["timestamp"], unique=False)
        batch_op.create_index(
            "ix_usage_records_timestamp_model", ["timestamp", "model"], unique=False
        )
        batch_op.create_index(
            "ix_usage_records_timestamp_provider", ["timestamp", "provider"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_usage_records_user_id"), ["user_id"], unique=False)

    op.create_table(
        "user_sessions",
        sa.Column("id", sa.String(length=36), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=False),
        sa.Column("token_hash", sa.String(length=64), nullable=False),
        sa.Column("token_prefix", sa.String(length=8), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(["user_id"], ["users.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_user_sessions_token_hash"), ["token_hash"], unique=True
        )
        batch_op.create_index(batch_op.f("ix_user_sessions_user_id"), ["user_id"], unique=False)

    op.create_table(
        "feedback_records",
        sa.Column("request_id", sa.String(length=64), nullable=False),
        sa.Column("signal", sa.String(length=16), nullable=False),
        sa.Column("model", sa.String(length=255), nullable=False),
        sa.Column("user_id", sa.Integer(), nullable=True),
        sa.Column("created_at", sa.Float(), nullable=False),
        sa.PrimaryKeyConstraint("request_id"),
    )

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("feedback_records")
    with op.batch_alter_table("user_sessions", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_user_sessions_user_id"))
        batch_op.drop_index(batch_op.f("ix_user_sessions_token_hash"))

    op.drop_table("user_sessions")
    with op.batch_alter_table("usage_records", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_usage_records_user_id"))
        batch_op.drop_index("ix_usage_records_timestamp_provider")
        batch_op.drop_index("ix_usage_records_timestamp_model")
        batch_op.drop_index("ix_usage_records_timestamp")
        batch_op.drop_index(batch_op.f("ix_usage_records_request_id"))
        batch_op.drop_index("ix_usage_records_provider")
        batch_op.drop_index("ix_usage_records_model")
        batch_op.drop_index("ix_usage_records_api_key")

    op.drop_table("usage_records")
    with op.batch_alter_table("model_providers", schema=None) as batch_op:
        batch_op.drop_index("ix_model_providers_provider_model_name")
        batch_op.drop_index("ix_model_providers_model_priority")

    op.drop_table("model_providers")
    op.drop_table("model_experience")
    with op.batch_alter_table("api_keys", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_api_keys_user_id"))

    op.drop_table("api_keys")
    with op.batch_alter_table("users", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_users_username"))

    op.drop_table("users")
    with op.batch_alter_table("server_config", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_server_config_key"))

    op.drop_table("server_config")
    with op.batch_alter_table("request_logs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_request_logs_user_id"))
        batch_op.drop_index("ix_request_logs_ts_status_model")
        batch_op.drop_index("ix_request_logs_total_tokens")
        batch_op.drop_index("ix_request_logs_timestamp_status")
        batch_op.drop_index("ix_request_logs_timestamp_sequence")
        batch_op.drop_index("ix_request_logs_timestamp")
        batch_op.drop_index("ix_request_logs_status_code")
        batch_op.drop_index(batch_op.f("ix_request_logs_sequence_number"))
        batch_op.drop_index("ix_request_logs_request_id")
        batch_op.drop_index("ix_request_logs_provider")
        batch_op.drop_index("ix_request_logs_outcome")
        batch_op.drop_index("ix_request_logs_model")
        batch_op.drop_index("ix_request_logs_event_type")
        batch_op.drop_index("ix_request_logs_cost_usd")
        batch_op.drop_index("ix_request_logs_client_ip")

    op.drop_table("request_logs")
    with op.batch_alter_table("providers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_providers_name"))

    op.drop_table("providers")
    with op.batch_alter_table("models", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_models_name"))

    op.drop_table("models")
    with op.batch_alter_table("mcp_servers", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_mcp_servers_name"))

    op.drop_table("mcp_servers")
    op.drop_table("audit_sequence")
    # ### end Alembic commands ###
